services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-fpiksurat
    volumes:
      - ./laravel:/var/www/html
    # command: chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
    networks:
      - app-bridge

  webserver:
    image: nginx:stable-alpine
    container_name: nginx-fpiksurat
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf   # Menyambungkan file konfigurasi Nginx
      - ./laravel:/var/www/html   # Menyambungkan folder app ke dalam container
    depends_on:
      - app   # Nginx harus menunggu app (PHP-FPM) siap
    networks:
      - app-bridge

  npm:
    image: node:20.17.0
    container_name: node-fpiksurat
    ports:
      - "5173:5173"
    volumes:
      - ./laravel:/var/www/html
    working_dir: /var/www/html
    command: npm run dev
    depends_on:
      - app   # Nginx harus menunggu app (PHP-FPM) siap
    networks:
      - app-bridge

networks:
  app-bridge:
    external: true